config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  post 'messenger/webhook' => 'messenger#receive_message'
  get 'done' => 'pages#done'
  get 'privacy' => 'pages#privacy'
  get 'contact' => 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/messagehuman.rb
class Messagehuman
  require 'json'


	def self.sendMessage(url, text)
		HTTParty.post(url.to_s, :body => { :response_type => 'ephemeral', :text => text}.to_json,
    :headers => { 'Content-Type' => 'application/json' })
	end

  def self.sendMessageAttach(url, text, attachment)
    HTTParty.post(url.to_s, :body => { :response_type => 'ephemeral', :text => text, :attachments => attachment}.to_json,
    :headers => { 'Content-Type' => 'application/json' })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messenger_controller.rb
class MessengerController < ApplicationController
	protect_from_forgery with: :null_session
	require 'httparty'
	require 'json'
	require 'cgi'

  def receive_message
    @webhook = CGI::parse(request.raw_post)
		@webhook["text"][0] = @webhook["text"][0].downcase
  #  puts @webhook
		if @webhook["text"][0] == "" || @webhook["text"][0] == " "
			@webhook["text"][0] = "tech"
		end
		if @webhook["text"][0].include?(" ")
			@webhook["text"][0].gsub!(" ", "-")
		end
		Messagehuman.sendMessage(@webhook["response_url"][0], "showing posts from #{@webhook["text"][0]}...")
    # getting the product hunt page that day
    @phPage = HTTParty.get("https://www.producthunt.com/topics/#{@webhook["text"][0]}")
    @phPage = @phPage.to_s

		if @webhook["text"][0] == "help"
			Messagehuman.sendMessage(@webhook["response_url"][0], "to use me: '/ph tech', or you can replace tech with: producitivy, developer-tools, games, books, bots, and many more!")
		elsif @phPage.include?("Page not found")
			Messagehuman.sendMessage(@webhook["response_url"][0], "sorry, we couldn't find that topic, try: tech, productivity, developer-tools")
		else


    	#trimming down the excess

	    @phPageArray = @phPage
			if @phPageArray.include?("Today")
				@phPageArray = @phPageArray.split('Today')
			else
				@phPageArray = @phPageArray.split('placeholder="Filter Posts"')
			end
	    @phPageArray.shift
	    @phPageArray = @phPageArray[0]
	    @phPageArray = @phPageArray.split('secondaryContent_cdfcd')
	    @phPageArray.pop
			@phPageArray = @phPageArray[0]
			#getting the titles
	    @phPageTitles = @phPageArray
			@phPageTitles = @phPageTitles.split('title_9ddaf">')
			@phPageTitles.shift
			@finalTitles = Array.new
	    @phPageTitles.each do |title|
			 	titleChar = title.split("")
				theTitle = String.new
				titleChar.each do |char|
					if char != "<"
						theTitle = theTitle + char
					else
						break
					end
				end
				break if @finalTitles.count == 5
				@finalTitles.push(theTitle)
			end
			#   puts @finalTitles

			# getting the ph turbolinks
			@phPageLinks = @phPageArray.split('link_523b9" href="')
			@phPageLinks.shift
			@finalLinks = Array.new
	    @phPageLinks.each do |link|
			 	linkChar = link.split("")
				theLink = String.new
				linkChar.each do |char|
					if char != '"'
						theLink = theLink + char
					else
						break
					end
				end
				break if @finalLinks.count == 5
				puts "THE LINK"
				puts theLink.inspect
				theLink = "https://www.producthunt.com" + theLink
				theLink.gsub!(" ", "-")
				puts theLink.inspect
				@finalLinks.push(theLink)
			end
			puts @finalLinks
			#   puts @finalLinks
			@phPageTagline = @phPageArray.split('tagline_619b7">')
			@phPageTagline.shift
			@finalTaglines = Array.new
	    @phPageTagline.each do |tagline|
			 	taglineChar = tagline.split("")
				theTagline = String.new
				taglineChar.each do |char|
					if char != '<'
						theTagline = theTagline + char
					else
						break
					end
				end
				break if @finalTaglines.count == 5
				@finalTaglines.push(theTagline)
			end

			@phPageVote = @phPageArray.split('<div class="icon_f5f81"></div> <!-- -->')
			@phPageVote.shift
			@finalVotes = Array.new
	    @phPageVote.each do |vote|
			 	voteChar = vote.split("")
				theVote = String.new
				voteChar.each do |char|
					if char != '<'
						theVote = theVote + char
					else
						break
					end
				end
				break if @finalVotes.count == 5
				@finalVotes.push(theVote)
			end

			#
			@phPageImg = @phPageArray.split('img src="')
			@phPageImg.shift
			@finalImgs = Array.new
	    @phPageImg.each do |img|
			 	imgChar = img.split("")
				theImg = String.new
				imgChar.each do |char|
					if char != '"'
						theImg = theImg + char
					else
						break
					end
				end
				break if @finalImgs.count == 5
				@finalImgs.push(theImg)
			end



			#puts @finalTaglines.inspect
				attachment = [
					{
						:thumb_url => "#{@finalImgs[0]}",
						:fallback => "#{@finalTitles[0]} - #{@finalTaglines[0]} - <#{@finalLinks[0]}>",
						:color => "#36a64f",
						:title => "#{@finalTitles[0]}",
						:title_link => "#{@finalLinks[0]}",
						:text => "#{@finalTaglines[0]}",
						fields: [
                {
                    title: "Vote Count: #{@finalVotes[0]}"
                }
            ]
					},
					{
						:thumb_url => "#{@finalImgs[1]}",
						:fallback => "#{@finalTitles[1]} - #{@finalTaglines[1]} - <#{@finalLinks[1]}>",
						:color => "#36a64f",
						:title => "#{@finalTitles[1]}",
						:title_link => "#{@finalLinks[1]}",
						:text => "#{@finalTaglines[1]}",
						fields: [
                {
                    title: "Vote Count: #{@finalVotes[1]}"
                }
            ]
					},
					{
						:thumb_url => "#{@finalImgs[2]}",
						:fallback => "#{@finalTitles[2]} - #{@finalTaglines[2]} - <#{@finalLinks[2]}>",
						:color => "#36a64f",
						:title => "#{@finalTitles[2]}",
						:title_link => "#{@finalLinks[2]}",
						:text => "#{@finalTaglines[2]}",
						fields: [
                {
                    title: "Vote Count: #{@finalVotes[2]}"
                }
            ]
					},
					{
						:thumb_url => "#{@finalImgs[3]}",
						:fallback => "#{@finalTitles[3]} - #{@finalTaglines[3]} - <#{@finalLinks[3]}>",
						:color => "#36a64f",
						:title => "#{@finalTitles[3]}",
						:title_link => "#{@finalLinks[3]}",
						:text => "#{@finalTaglines[3]}",
						fields: [
                {
                    title: "Vote Count: #{@finalVotes[3]}"
                }
            ]
					},
					{
						:thumb_url => "#{@finalImgs[4]}",
						:fallback => "#{@finalTitles[4]} - #{@finalTaglines[4]} - <#{@finalLinks[4]}>",
						:color => "#36a64f",
						:title => "#{@finalTitles[4]}",
						:title_link => "#{@finalLinks[4]}",
						:text => "#{@finalTaglines[4]}",
						fields: [
                {
                    title: "Vote Count: #{@finalVotes[4]}"
                }
            ]
					}
				]
			Messagehuman.sendMessageAttach(@webhook["response_url"][0], "", attachment)
		end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def privacy
  end

  def done
		thecode = params["code"]
    puts thecode
		if !thecode.nil?
			puts "THE TOKEN!"
			@theToken = HTTParty.get("https://slack.com/api/oauth.access?client_id=219592720864.285551398295&client_secret=6546a0cc240d1946aa66f60f6bbcacd3&code=#{thecode}")
			puts @theToken
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Producthunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="top-thin">
<h1 class="center black"> Need Some Help? </h1>
<p class="center black"> I would be happy to assist you! Shoot me an email at <b>alecaej2002@gmail.com</b> and I will get back to you pronto.
</p>
</div>

<div class="center">
  <p> <%= link_to "Home", root_path %> | <%= link_to "Privacy Policy", privacy_path %> | <%= link_to "Contact Us", contact_path %> </p>
</div>

app/views/pages/done.html.erb
<div class="center">
  <h1 class="title"> Yay! You're All Set To Use Slash PH! </h1><br>
  <%= image_tag("https://media.giphy.com/media/xUOxf4hYse3e8vrRcI/giphy.gif", class: "image") %><br>
</div>
<div class="center">
  <p> <%= link_to "Home", root_path %> | <%= link_to "Privacy Policy", privacy_path %> | <%= link_to "Contact Us", contact_path %> </p>
</div>

app/views/pages/index.html.erb
<!--[if lt IE 7]>
    <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->


<div class="banner">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="banner-content">
                    <h2>Slash <b>PH</b></h2>
                    <h6>The Product Hunt powered slash command</h6>
                    <br>
                    <ul class="buttons">
                        <a href="https://slack.com/oauth/authorize?client_id=219592720864.285551398295&scope=commands"><%= image_tag("slack-button.png") %></a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="intro">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h4>“/ph topic”</h4>
                        <h6>Use /ph and any PH topic, and we'll return top 5 products in that topic today</h6>
                    </div>
                </div>
            </div>
        </div>


<section id="about" class="page-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="service-item first-service">
                    <div class="icon">
                        <%= image_tag("third-service-icon.png") %>
                    </div>
                    <h4>"/PH TECH"</h4>
                    <p>see the top 5 tech posts today</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="service-item second-service">
                    <div class="icon">
                          <%= image_tag("third-service-icon.png") %>
                    </div>
                    <h4>/PH BOTS</h4>
                    <p>see the top 5 bot posts today</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="service-item third-service">
                    <div class="icon">
                        <%= image_tag("third-service-icon.png") %>
                    </div>
                    <h4>/PH PRODUCTIVITY</h4>
                    <p>see the top 5 tech productivity tools today</p>
                </div>
            </div>
        </div>
    </div>
</section>

<footer id="footer" class="center">
  <div class="container">
      <div class="row">
          <div class="center">
            <p class="white"> <%= link_to "Home", root_path %> | <%= link_to "Privacy Policy", privacy_path %> | <%= link_to "Contact Us", contact_path %> </p>
          </div>
      </div>
  </div>
</footer>

app/views/pages/privacy.html.erb
<div class="thin black">
<h1 class="center black">Slash PH Privacy Policy</h1>
<h2>Information we collect</h2>

<p>Slash PH for Slack is just for fun. We store <u><b>none</b></u> of your data - nothing</p>

<h2>Do we use cookies?</h2>

<p>Nope.</p>

<h2>Third party links</h2>

<p>Occasionally, at our discretion, we may include or offer third party products or services on our website.
These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites.
Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>

<h2>Your consent </h2>

<p>By using our site, you consent to our privacy policy.</p>

<h2>Changes to our privacy policy</h2>

<p>If we decide to change our privacy policy, we will post the changes on this page.
Last updated on December 18th, 2017.</p>

<h2>Contacting us</h2>

<p>If you have any questions regarding this privacy policy you may contact Alec Jones here: <b>alecaej2002@gmail.com</b></p>
</div>
<div class="center">
  <p> <%= link_to "Home", root_path %> | <%= link_to "Privacy Policy", privacy_path %> | <%= link_to "Contact Us", contact_path %> </p>
</div>